transit_data_analytics_demo:
  target: prod
  outputs:
    prod: &prod
      dataset: staging
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: us-east4
      method: oauth
      priority: interactive
      project: transit-data-analytics-demo
      threads: 4
      type: bigquery
      maximum_bytes_billed: 100000000000
    prod_service_account:
      <<: *prod
      method: service-account
      keyfile: "{{ env_var('BIGQUERY_SERVICE_ACCOUNT') }}"
