{{- if eq .Values.runLauncher.type "CeleryK8sRunLauncher" }}
{{- $celeryK8sRunLauncherConfig := .Values.runLauncher.config.celeryK8sRunLauncher }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dagster.fullname" . }}-celery-worker-env
  labels:
    app: {{ template "dagster.name" . }}
    chart: {{ template "dagster.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- include "dagster.shared_env" . | nindent 2 }}

  {{- range $name, $value := $celeryK8sRunLauncherConfig.env }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
{{- end }}
