apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dagster.fullname" . }}-pipeline-env
  labels:
    app: {{ template "dagster.name" . }}
    chart: {{ template "dagster.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ include "dagster.shared_env" . | nindent 2 }}

  {{- range $name, $value := .Values.pipelineRun.env }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}

  {{- if eq .Values.runLauncher.type "CeleryK8sRunLauncher" }}
  {{- range $name, $value := .Values.runLauncher.config.celeryK8sRunLauncher.env }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
