{{- if .Values.dagsterDaemon.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dagster.fullname" $ -}}-daemon-env
  labels:
    app: {{ template "dagster.name" $ }}
    chart: {{ template "dagster.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
data:
  {{ include "dagster.shared_env" $ | nindent 2 }}
  # This is a list by default, but for backcompat it can be a map. If it's a list, the env is applied directly
  # to the container.
  {{- if and (.Values.dagsterDaemon.env) (kindIs "map" .Values.dagsterDaemon.env) }}
  {{- range $name, $value := .Values.dagsterDaemon.env }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
---
{{ end }}
