{{- $_ := include "dagster.backcompat" . | mustFromJson -}}
{{- $data := dict "Values" .Values "Release" .Release "Chart" .Chart "Template" .Template -}}
{{- include "service-webserver" $data -}}

{{- if $_.Values.dagsterWebserver.enableReadOnly -}}
---
{{$data := dict "Values" .Values "Release" .Release "Chart" .Chart "Template" .Template "webserverReadOnly" true}}
{{- include "service-webserver" $data -}}
{{- end -}}
