apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  labels:
    app.kubernetes.io/instance: metabase
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: metabase
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: metabase-0.1.0
  name: metabase
  namespace: metabase
spec:
  rules:
    - host: metabase.k8s.tdad.jarv.us
      http:
        paths:
          - backend:
              service:
                name: metabase
                port:
                  number: 3000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - metabase.k8s.tdad.jarv.us
      secretName: metabase-tls
