apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ticker
  name: ticker
  namespace: fetcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticker
  template:
    metadata:
      annotations:
        prometheus.io/port: '8000'
        prometheus.io/scrape: 'true'
      labels:
        app: ticker
    spec:
      containers:
        - command:
            - python
            - '-m'
            - fetcher.ticker
          envFrom:
            - configMapRef:
                name: fetcher-config
          image: >-
            ghcr.io/jarvusinnovations/transit-data-analytics-demo/fetcher:2025.11.21
          imagePullPolicy: Always
          name: ticker
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /etc/gcs-secret
              name: gcs-secret
              readOnly: true
      volumes:
        - name: gcs-secret
          secret:
            secretName: fetcher-secret
