apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app.kubernetes.io/instance: dagster
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dagster
    app.kubernetes.io/version: dev
    component: dagster-webserver
    helm.sh/chart: dagster-0.0.1-dev
  name: dagster-dagster-webserver
  namespace: dagster
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    app.kubernetes.io/instance: dagster
    app.kubernetes.io/name: dagster
    component: dagster-webserver
  type: ClusterIP
