apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
    chart: postgresql-8.1.0
    heritage: Helm
    release: dagster
  name: dagster-postgresql
  namespace: dagster
spec:
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app: postgresql
    release: dagster
    role: master
  type: ClusterIP
