{{ range $deployment := .Values.deployments }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dagster.fullname" $ -}}-{{- $deployment.name }}-user-env
  labels:
    app: {{ template "dagster.name" $ }}
    chart: {{ template "dagster.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
data:
  # If this is a map, we write it to this configmap. If it's a list, we include it
  # directly on the container (can use more k8s spec like valueFrom).
  {{- if and ($deployment.env) (kindIs "map" $deployment.env) }}
  {{- range $name, $value := $deployment.env }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
---
{{ end }}
