---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dagster.fullname" $ -}}-user-deployments-shared-env
  labels:
    app: {{ template "dagster.name" $ }}
    chart: {{ template "dagster.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
data:
  {{ include "dagsterUserDeployments.sharedEnv" $ | nindent 2 }}

---
