{{- if .Values.rbacEnabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "dagster.fullname" . }}-rolebinding
  labels: {{ include "dagster.labels" . | nindent 4 }}

subjects:
- kind: ServiceAccount
  name: {{ include "dagsterUserDeployments.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "dagster.fullname" . }}-role
{{- end -}}