apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: null
  labels:
    app.kubernetes.io/instance: dagster
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dagster
    app.kubernetes.io/version: dev
    component: dagster-daemon
    deployment: daemon
    helm.sh/chart: dagster-0.0.1-dev
  name: dagster-daemon
  namespace: dagster
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dagster
      app.kubernetes.io/name: dagster
      component: dagster-daemon
      deployment: daemon
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/dagster-instance: e6733c7dfa9e57aa0639954b05111a833c35c696747adddfd8b4fe9000626924
        checksum/dagster-workspace: 72d6bd47596ae6465d27c9b714b33f4c5270973e83cf94d2defcae75c5e8cfe5
      labels:
        app.kubernetes.io/instance: dagster
        app.kubernetes.io/name: dagster
        component: dagster-daemon
        deployment: daemon
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - postgresql
                topologyKey: topology.kubernetes.io/zone
              weight: 100
      containers:
        - command:
            - /bin/bash
            - '-c'
            - dagster-daemon run -w /dagster-workspace/workspace.yaml
          env:
            - name: DAGSTER_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgresql-password
                  name: dagster-postgresql-secret
            - name: DAGSTER_DAEMON_HEARTBEAT_TOLERANCE
              value: '300'
          envFrom:
            - configMapRef:
                name: dagster-daemon-env
          image: docker.io/dagster/dagster-celery-k8s:1.4.10
          imagePullPolicy: Always
          name: dagster
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext: {}
          volumeMounts:
            - mountPath: /opt/dagster/dagster_home/dagster.yaml
              name: dagster-instance
              subPath: dagster.yaml
            - mountPath: /dagster-workspace/
              name: dagster-workspace-yaml
      imagePullSecrets: []
      initContainers:
        - command:
            - sh
            - '-c'
            - >-
              until pg_isready -h dagster-postgresql -p 5432 -U test; do echo
              waiting for database; sleep 2; done;
          image: library/postgres:14.6
          imagePullPolicy: IfNotPresent
          name: check-db-ready
          securityContext: {}
        - command:
            - sh
            - '-c'
            - >-
              until nslookup tdad-dags; do echo waiting for user service; sleep
              2; done
          image: docker.io/busybox:1.28
          name: init-user-deployment-tdad-dags
      nodeSelector: {}
      securityContext: {}
      serviceAccountName: dagster
      tolerations: []
      volumes:
        - configMap:
            name: dagster-instance
          name: dagster-instance
        - configMap:
            name: dagster-workspace-yaml
          name: dagster-workspace-yaml
