apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fetcher-test
resources:
  - ../../manifests/fetcher/
  - config.yaml
  - ns.yaml
patches:
- path: consumer.patch.yaml
  target:
    name: consumer
- path: ticker.patch.yaml
  target:
    name: ticker
