run:
  echo_format: "{command}"
  echo: true
jarvus:
  deployments:
    # applications
    - name: fetcher
      namespace: fetcher
      driver: kustomize
      path: kubernetes/overlays/fetcher-prod

    # base services
    - name: cert-manager
      namespace: cert-manager
      driver: helm
      chart: kubernetes/charts/cert-manager
      dependency: false
    - name: grafana
      namespace: grafana
      driver: helm
      chart: kubernetes/charts/grafana
      values:
        - kubernetes/values/prod-grafana.yml
    - name: ingress-nginx
      namespace: ingress-nginx
      driver: helm
      chart: kubernetes/charts/ingress-nginx
    - name: loki
      namespace: loki
      driver: helm
      chart: kubernetes/charts/loki
    - name: prometheus
      namespace: prometheus
      driver: helm
      chart: kubernetes/charts/prometheus
    - name: promtail
      namespace: promtail
      driver: helm
      chart: kubernetes/charts/promtail
