apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: dagster
    chart: dagster-0.0.1-dev
    heritage: Helm
    release: dagster
  name: dagster-rolebinding
  namespace: dagster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dagster-role
subjects:
  - kind: ServiceAccount
    name: dagster
