name: Build candidate branch

on:
  push:
    branches:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: JarvusInnovations/hologit@actions/projector/v1
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_ACTION }}
          HAB_LICENSE: accept
        with:
          holobranch: release-candidate
          commit-to: "candidates/${{github.ref_name}}"
