name: Build candidate branch

on:
  push:
    branches:
      - "*"

env:
  GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
  HAB_LICENSE: accept-no-persist

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: JarvusInnovations/hologit@actions/projector/v1
        with:
          holobranch: release-candidate
          commit-to: "candidates/${{GITHUB_REF#refs/heads/}}"
