name: Release deploy

on:
  push:
    branches:
      - releases/*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: branch-names
        uses: tj-actions/branch-names@v2.1
      - uses: actions/setup-python@v4
      - uses: abatilo/actions-poetry@v2
